// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcuAT_neyVTDsvaYeO24i7VF5uemtcH4c',
    appId: '1:120244845106:web:f84c91909311392c279a2b',
    messagingSenderId: '120244845106',
    projectId: 'familyhealth3',
    authDomain: 'familyhealth3.firebaseapp.com',
    storageBucket: 'familyhealth3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQW2f59UQsqTd7tC0oKX4RNcIK7EpOgm0',
    appId: '1:120244845106:android:4998e516821830ac279a2b',
    messagingSenderId: '120244845106',
    projectId: 'familyhealth3',
    storageBucket: 'familyhealth3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFKQTEb4zztCQLVBYNmv9sWUAZEalAkhs',
    appId: '1:120244845106:ios:2c55475c47702a1c279a2b',
    messagingSenderId: '120244845106',
    projectId: 'familyhealth3',
    storageBucket: 'familyhealth3.firebasestorage.app',
    iosBundleId: 'my.family',
  );
}
